[package]
name = "p0606_construct_string_from_binary_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tools = { path = "../tools" }
