[package]
name = "p1461_check_if_a_string_contains_all_binaly_codes_of_size_k"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
